### ISSUE TITLE
maybe illegal  character caused redisql to shutdown?

### ISSUE THREAD

**Issue by xiao321** [RedBeardLab/rediSQL#77] opened 2019-07-19 09:55 UTC
env:
redis 5.0.3 + redisql 1.0.3

illegal character caused redisql to shutdown?
i checked my data , they are normal. just include null, nan, '' .   i think it is resolved in redisql 1.0.3.
https://github.com/RedBeardLab/rediSQL/issues/66#issuecomment-506282874

![image](https://user-images.githubusercontent.com/6407725/61527063-341d0980-aa4e-11e9-89f1-c4c9fc584c5b.png)

**Comment by siscia** [comment] 2019-07-19 10:08
Sorry, didn't get it!

Does it causes a panic in the latest rc? Because it should be fixed in the last version of the code.

Otherwise I need to look into it!

**Comment by xiao321** [comment] 2019-07-19 10:12
> Sorry, didn't get it!
> 
> Does it causes a panic in the latest rc? Because it should be fixed in the last version of the code.
> 
> Otherwise I need to look into it!

redisql 1.0.3-rc02

**Comment by siscia** [comment] 2019-07-19 11:16
The problem is also on 1.0.3-rc2 or not?

**Comment by xiao321** [comment] 2019-07-19 11:43
> The problem is also on 1.0.3-rc2 or not?

maybe yes

**Comment by siscia** [comment] 2019-08-19 17:25
Can this be closed or the problem is actually there?

**Closed** 2020-05-03 10:07 UTC
