### ISSUE TITLE
Crash at redis server start when sqlite file is deleted

### ISSUE THREAD

**Issue by salt4pommes** [RedBeardLab/rediSQL#41] opened 2019-03-25 13:46 UTC
23189:C 25 Mar 2019 14:39:44.911 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
23189:C 25 Mar 2019 14:39:44.911 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=23189, just started
23189:C 25 Mar 2019 14:39:44.911 # Configuration loaded
23189:M 25 Mar 2019 14:39:44.913 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
23189:M 25 Mar 2019 14:39:44.913 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
23189:M 25 Mar 2019 14:39:44.913 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
23189:M 25 Mar 2019 14:39:44.914 * Running mode=standalone, port=6381.
23189:M 25 Mar 2019 14:39:44.914 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
23189:M 25 Mar 2019 14:39:44.914 # Server initialized
23189:M 25 Mar 2019 14:39:44.914 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
23189:M 25 Mar 2019 14:39:44.915 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
23189:M 25 Mar 2019 14:39:44.916 * <ft> Configuration: concurrent mode: 1, ext load: (null), min prefix: 2, max expansions: 200, query timeout: 500ms, timeout policy: return
23189:M 25 Mar 2019 14:39:44.917 * <ft> Initialized thread pool!
23189:M 25 Mar 2019 14:39:44.918 * Module 'ft' loaded from /home/willi/.redis/redisearch.so
23189:M 25 Mar 2019 14:39:44.918 * Module 'rediSQL' loaded from /home/willi/.redis/redisql.so
23189:M 25 Mar 2019 14:39:44.922 * <graph> Thread pool created, using 8 threads.
23189:M 25 Mar 2019 14:39:44.922 * Module 'graph' loaded from /home/willi/.redis/redisgraph.so
23189:M 25 Mar 2019 14:39:44.922 * Reading RDB preamble from AOF file...
23189:M 25 Mar 2019 14:39:44.922 # Error loading data from RDB (short read or EOF). Read performed by module 'rediSQL' about type 'rediSQLDB' after reading '0' bytes of a value.

**Comment by siscia** [comment] 2019-03-25 14:29
Can you elaborate a little?

If I guess correctly you created a RediSQL file backed database with something like:

REDISQL.CREATE_DB FOO /home/foo/db.sqlite

Then you stopped redis, deleted the file and then try to restart the server again.

Is that correct?

In the meantime I see you saved the dataset on RDB so the problem is about re-reading a file saved on RDB, right?

**Comment by salt4pommes** [comment] 2019-03-25 15:46
I used a file backend like this REDISQL.CREATE_DB FOO /home/foo/db.sqlite.

Yes, thats the workflow :) And the dataset is saved as AOF using RDB preamble

**Comment by siscia** [comment] 2019-03-25 18:16
Thanks!

I will look into it and report back! 

Allow me a couple of days though

**Comment by digo1985** [comment] 2019-03-26 10:09
redisql.create_statement DB 'INSERT INTO  table_aa (A,B) VALUES (?1,?2);'

there appears error
 (error) Wrong number of arguments, it accepts 4

and I change the command like  redisql.create_statement DB 'INSERT INTO  table_aa (A,B) VALUES (?,?);'
the error also appears.

**Comment by siscia** [comment] 2019-03-27 10:30
I thought quite a bit about this, and I recall what is the rationale behind the crash.

I would like your feedback on the behaviour of loading from RDB a database backed by file.

We started by creating a db:
`REDISQL.CREATE_DB foo /home/foo/db.sqlite`
Then we create a RDB file.

Now, few scenarios opens.

1. You re-load the RDB, the `db.sqlite` file is on the machine.
Should we just open the `db.sqlite` file or we should load the whole db from the RDB file? If we load the DB from the RDB file, what shuld happen to the original `db.sqlite` file? Should it get deleted? Should it stay there? If it stays there, how should I call the new `db.sqlite` file? Something like `db.sqlite(1)`?

2. You re-load the RDB, the `db.sqlite` file is not on the machine.
Should we just load the database from the RDB file or should we just fail? If we just fail we tell the user that something bad happen and that it should be carefull.

I don't see a clear answer on all the cases, what did you expected? How you think should all this be handled?

**Comment by salt4pommes** [comment] 2019-03-29 09:29
I think the best option is to let the user decide.

Maybe there should be a flag to import the whole db.sqlite to rdb.
When the db is imported, the db.sqlite could stay but won't touched again.

If user desides to not import the db.sqlite, there should be a warning that the file is missing and the db could not be loaded.

What do you think?

**Comment by siscia** [comment] 2019-03-29 17:00
I don't like to give users options, ideally, I should provide the dumbest possible interface that cannot be misused. Moreover, I would need to pass the flag when loading the module or when creating the DB, which seems like a bad UI.

I am thinking of saving the DB on the RDB file and on loading, if the file is present, load the file, if it is not present, load the file from RDB. If the file is present, but cannot be loaded as SQLite DB (maybe a corrupted file or a different type of file), refuse to start with an error.

Another option would be to save a unique identifier (uuidv4?) in the database and load the database from the file if and only if the identifiers (the one saved in the RDB database and the one in the file) match. But this would make the loading quite slow, which in general should be avoided.

Do you see potential problems with the first option?

**Comment by siscia** [comment] 2019-04-04 14:05
This should be addressed by the v0.9.3!

**Closed by siscia** 2019-04-04 14:05 UTC
