### ISSUE TITLE
is there a way to quickly determine if a database is unavailable?

### ISSUE THREAD

**Issue by xiao321** [RedBeardLab/rediSQL#78] opened 2019-07-22 11:34 UTC
is there a way to quickly determine if a database is unavailable? The response is at the millisecond level.

**Comment by siscia** [comment] 2019-07-22 12:10
databases should not become unavailable, if you guys provide tests for when a db become unavailable we will work on it together.

I will suggest to try to test if the redis key associate with the db exists.

**Comment by siscia** [comment] 2019-07-24 07:03
Ahhhhh I see what you guys mean!

Please confirm if this is what you see:

1. You run a long query
2. RediSQL just work, but it does not reply yet
3. Further commands are ignored
4. One core is at high usage (like 100%)
5. Eventually everything starts to work again

Is this correct?

**Comment by xiao321** [comment] 2019-07-25 06:27
> Ahhhhh I see what you guys mean!
> 
> Please confirm if this is what you see:
> 
> 1. You run a long query
> 2. RediSQL just work, but it does not reply yet
> 3. Further commands are ignored
> 4. One core is at high usage (like 100%)
> 5. Eventually everything starts to work again
> 
> Is this correct?

1、yes. maybe more than one
2、yes.
3、yes. after 10 sencods，no result , received nill.
4、sorry, no attention was paid the case.
5、when the database can not response normally，i will restart it.

**Comment by siscia** [comment] 2019-07-25 07:12
Very well!

If next time it happen you could monitor the CPU usage and confirm the hypothesis it would be amazing!

Anyway I am going to fix it! It is not a trivial effort and it requires some time. But we are in a good position!

**Comment by xiao321** [comment] 2019-07-30 03:42
> Very well!
> 
> If next time it happen you could monitor the CPU usage and confirm the hypothesis it would be amazing!
> 
> Anyway I am going to fix it! It is not a trivial effort and it requires some time. But we are in a good position!

i have three tables. A table with 30000 data.  B table with 30000 data. C table with 30000 data.
sql like this:
select ... from A left join B on A.id=B.id and A.name=B.name left join C on A.id=C.id and A.name=C.name .

i run it , then i see the result: high cpu, high memory
![image](https://user-images.githubusercontent.com/6407725/62098779-5e788d80-b2be-11e9-9ef4-b88ff8e69284.png)

i waited for 10 minutes，the database also can not work.   Restart is the only way .

**Comment by siscia** [comment] 2019-07-30 08:37
Ok, the latest code should kill it when it reach 10 seconds!

Yesterday I fell sick so I wasn't able to compile it for you! Sorry I will try to do it today!

**Comment by siscia** [comment] 2019-07-31 19:53
Do you guys mind to try the latest release?

https://github.com/RedBeardLab/rediSQL/releases/tag/v1.0.3-rc04

**Comment by siscia** [comment] 2019-08-06 09:21
Guys, I am not receiving any more feedback from you.

At the moment I am closing this issue and eventually I will close all the other.

Either the problem was fixed with the last RC, the problem is not important, or you don't have time to follow up on these.

In all cases I am closing the issue, feel free to re-open!

**Closed by siscia** 2019-08-06 09:21 UTC
